import { Category, Product } from '@/types/menu';
import { Recipe } from '@/types/recipe';
import {
  ConsumptionType,
  DeliverySource,
  DeliveryStatus,
  ProductCategory,
  ProductType,
  SalesChannel,
  VatRate,
} from '@/types/enums';
import { InventoryCategory, StockItem, Warehouse } from '@/types/inventory';
import { Supplier } from '@/types/delivery';

export const E2E_IDS = {
  warehouse: '11111111-1111-4111-8111-111111111111',
  inventoryCategory: '22222222-2222-4222-8222-222222222222',
  category: '33333333-3333-4333-8333-333333333333',
  stockBeef: '44444444-4444-4444-8444-444444444441',
  stockBuns: '44444444-4444-4444-8444-444444444442',
  stockCheddar: '44444444-4444-4444-8444-444444444443',
  stockTomato: '44444444-4444-4444-8444-444444444444',
  recipeSauceBase: '55555555-5555-4555-8555-555555555551',
  recipeSauceChild: '55555555-5555-4555-8555-555555555552',
  recipePatty: '55555555-5555-4555-8555-555555555553',
  productFormRecipe: '66666666-6666-4666-8666-666666666661',
  supplier: '77777777-7777-4777-8777-777777777771',
  delivery: '88888888-8888-4888-8888-888888888881',
} as const;

const now = '2026-03-06T10:00:00.000Z';

export const e2eWarehouses: Warehouse[] = [
  {
    id: E2E_IDS.warehouse,
    name: 'Magazyn E2E',
    location_id: null,
    is_active: true,
    is_default: true,
    created_at: now,
    updated_at: now,
  },
];

export const e2eInventoryCategories: InventoryCategory[] = [
  {
    id: E2E_IDS.inventoryCategory,
    name: 'Surowce E2E',
    description: 'Fixtures do testow przegladarkowych',
    sort_order: 1,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export const e2eStockItems: StockItem[] = [
  {
    id: E2E_IDS.stockBeef,
    name: 'Wolowina E2E',
    sku: 'E2E-BEEF',
    inventory_category_id: E2E_IDS.inventoryCategory,
    product_category: ProductCategory.RAW_MATERIAL,
    unit: 'kg',
    cost_per_unit: 32,
    purchase_unit_weight_kg: 2.5,
    allergens: [],
    is_active: true,
    vat_rate: VatRate.PTU_B,
    consumption_type: ConsumptionType.PRODUCT,
    shelf_life_days: 5,
    default_min_quantity: 2,
    storage_location: 'Chlodnia',
    created_at: now,
    updated_at: now,
  },
  {
    id: E2E_IDS.stockBuns,
    name: 'Bulka E2E',
    sku: 'E2E-BUN',
    inventory_category_id: E2E_IDS.inventoryCategory,
    product_category: ProductCategory.RAW_MATERIAL,
    unit: 'szt',
    cost_per_unit: 1.2,
    purchase_unit_weight_kg: null,
    allergens: [],
    is_active: true,
    vat_rate: VatRate.PTU_B,
    consumption_type: ConsumptionType.PRODUCT,
    shelf_life_days: 3,
    default_min_quantity: 20,
    storage_location: 'Regal A',
    created_at: now,
    updated_at: now,
  },
  {
    id: E2E_IDS.stockCheddar,
    name: 'Cheddar E2E',
    sku: 'E2E-CHED',
    inventory_category_id: E2E_IDS.inventoryCategory,
    product_category: ProductCategory.RAW_MATERIAL,
    unit: 'kg',
    cost_per_unit: 28,
    purchase_unit_weight_kg: null,
    allergens: [],
    is_active: true,
    vat_rate: VatRate.PTU_B,
    consumption_type: ConsumptionType.PRODUCT,
    shelf_life_days: 7,
    default_min_quantity: 2,
    storage_location: 'Chlodnia',
    created_at: now,
    updated_at: now,
  },
  {
    id: E2E_IDS.stockTomato,
    name: 'Pomidor E2E',
    sku: 'E2E-TOM',
    inventory_category_id: E2E_IDS.inventoryCategory,
    product_category: ProductCategory.RAW_MATERIAL,
    unit: 'kg',
    cost_per_unit: 8,
    purchase_unit_weight_kg: null,
    allergens: [],
    is_active: true,
    vat_rate: VatRate.PTU_B,
    consumption_type: ConsumptionType.PRODUCT,
    shelf_life_days: 7,
    default_min_quantity: 2,
    storage_location: 'Chlodnia',
    created_at: now,
    updated_at: now,
  },
];

export const e2eRecipes: Recipe[] = [
  {
    id: E2E_IDS.recipeSauceBase,
    product_id: E2E_IDS.productFormRecipe,
    name: 'Sos bazowy E2E',
    description: 'Bazowy polprodukt wagowy do testow',
    product_category: ProductCategory.SEMI_FINISHED,
    ingredients: [
      {
        id: 'ingredient-sauce-base',
        type: 'stock_item',
        reference_id: E2E_IDS.stockTomato,
        reference_name: 'Pomidor E2E',
        quantity: 1,
        unit: 'kg',
      },
    ],
    yield_quantity: 1,
    yield_unit: 'kg',
    preparation_time_minutes: 15,
    instructions: 'Wymieszaj skladniki',
    allergens: [],
    total_cost: 8,
    cost_per_unit: 8,
    food_cost_percentage: null,
    version: 1,
    is_active: true,
    created_by: 'system',
    last_updated_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: E2E_IDS.recipeSauceChild,
    product_id: '66666666-6666-4666-8666-666666666662',
    name: 'Sos pochodny E2E',
    description: 'Potomek receptury bazowej',
    product_category: ProductCategory.SEMI_FINISHED,
    ingredients: [
      {
        id: 'ingredient-sauce-child',
        type: 'recipe',
        reference_id: E2E_IDS.recipeSauceBase,
        reference_name: 'Sos bazowy E2E',
        quantity: 0.5,
        unit: 'kg',
      },
    ],
    yield_quantity: 1,
    yield_unit: 'kg',
    preparation_time_minutes: 5,
    instructions: 'Dodaj przyprawy',
    allergens: [],
    total_cost: 4,
    cost_per_unit: 4,
    food_cost_percentage: null,
    version: 1,
    is_active: true,
    created_by: 'system',
    last_updated_by: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: E2E_IDS.recipePatty,
    product_id: '66666666-6666-4666-8666-666666666663',
    name: 'Patty E2E',
    description: 'Polprodukt sztukowy do testow',
    product_category: ProductCategory.SEMI_FINISHED,
    ingredients: [
      {
        id: 'ingredient-patty',
        type: 'stock_item',
        reference_id: E2E_IDS.stockBeef,
        reference_name: 'Wolowina E2E',
        quantity: 0.15,
        unit: 'kg',
      },
    ],
    yield_quantity: 1,
    yield_unit: 'szt',
    preparation_time_minutes: 6,
    instructions: 'Uformuj patty',
    allergens: [],
    total_cost: 4.8,
    cost_per_unit: 4.8,
    food_cost_percentage: null,
    version: 1,
    is_active: true,
    created_by: 'system',
    last_updated_by: null,
    created_at: now,
    updated_at: now,
  },
];

export const e2eCategories: Category[] = [
  {
    id: E2E_IDS.category,
    name: 'Burgery E2E',
    slug: 'burgery-e2e',
    description: 'Kategoria do testow formularza produktu',
    sort_order: 1,
    is_active: true,
    color: 'from-amber-500 to-orange-600',
    icon: 'burger',
    created_at: now,
    updated_at: now,
  },
];

export const e2eSuppliers: Supplier[] = [
  {
    id: E2E_IDS.supplier,
    name: 'Dostawca E2E',
    phone: null,
    email: null,
    notes: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export function createProductFixture(): Product {
  return {
    id: E2E_IDS.productFormRecipe,
    name: 'Burger E2E',
    slug: 'burger-e2e',
    description: 'Produkt roboczy do testow',
    category_id: E2E_IDS.category,
    type: ProductType.SINGLE,
    price: 29.9,
    food_cost_percentage: null,
    original_price: null,
    promo_label: null,
    promo_starts_at: null,
    promo_ends_at: null,
    image_url: undefined,
    images: [],
    is_available: true,
    is_featured: false,
    allergens: [],
    nutritional_info: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
    },
    variants: [],
    modifier_groups: [],
    ingredients: [],
    recipe_id: undefined,
    preparation_time_minutes: 10,
    sort_order: 1,
    color: 'from-amber-500 to-orange-600',
    sku: 'E2E-PROD',
    tax_rate: 8,
    is_active: true,
    point_ids: [],
    pricing: [
      { channel: SalesChannel.EAT_IN, price: 29.9 },
      { channel: SalesChannel.DELIVERY, price: 31.9 },
    ],
    created_at: now,
    updated_at: now,
  };
}

export const e2eDeliveryDraft = {
  id: E2E_IDS.delivery,
  delivery_number: 'PZ E2E/1',
  warehouse_id: E2E_IDS.warehouse,
  supplier_id: E2E_IDS.supplier,
  document_number: null,
  document_date: null,
  source: DeliverySource.MANUAL,
  source_image_url: null,
  notes: null,
  status: DeliveryStatus.DRAFT,
  created_at: now,
  updated_at: now,
};
